baseURL: "https://jermanuts.vercel.app/"
languageCode: en-us
title: Jermanuts
theme: WonderMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true

params:
 env: production
 title: Jermanuts
 description: Research on security and privacy.
 keywords: [Blog, Research, Security, Privacy] 
 author: Jermanuts
 DateFormat: "January 2, 2006"
 defaultTheme: dark # dark, light
 disableThemeToggle: false
 ShowFullTextinRSS: true
  # for search
  # https://fusejs.io/api/options.html
 fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]
 assets:
    disableHLJS: true
    disableFingerprinting: false   

 homeInfoParams:
   Title: "Hi there."
   Content: Research on security and privacy.

 socialIcons:
   - name: github
     url: "https://github.com/jermanuts"
   - name: rss
     url: /index.xml

 ShowReadingTime: true
 ShowShareButtons: false
 ShowPostNavLinks: true
 ShowBreadCrumbs: true
 ShowCodeCopyButtons: true
 ShowFullTextinRSS: true
 disableSpecial1stPost: false
 disableScrollToTop: false
 comments: false
 hidemeta: false
 hideSummary: false
 showtoc: true
 tocopen: false

outputs:
  home:
    - HTML
    - RSS
    - JSON


    



markup:
    highlight:
        style: dracula
        noClasses: false
        guessSyntax: true

menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: Search
          name: Search
          url: /search/
          weight: 30

